//
// Created by Agamjeet Singh on 26/08/25.
//

#ifndef SOUNDEFFECT_H
#define SOUNDEFFECT_H



enum class SoundEffect {
    DASH_LEFT,
    DASH_RIGHT,
    LAND,
    TOUCH_SWITCH_ACTIVATE,
    TOUCH_SWITCH_ALL_ACTIVATE,
    DEATH,
    DIAMOND_TOUCH_01,
    DIAMOND_TOUCH_02,
    DIAMOND_TOUCH_03,
    DIAMOND_RETURN_01,
    DIAMOND_RETURN_02,
    DIAMOND_RETURN_03,
    SWAP_BLOCK_MOVE,
    SWAP_BLOCK_RETURN_LOOP_INTRO,
    SWAP_BLOCK_RETURN_LOOP,
    SWAP_BLOCK_RETURN_LOOP_END
};


#endif //SOUNDEFFECT_H
